### ISSUE TITLE
Adding Ranks

### ISSUE THREAD

**Issue by RandomMonkey99** [Lxca128/SlimeRanks#19]
Hello @Lxca128,
I would ask you to help me adding ranks and using textured text because you don't made a wiki.

**Comment by Lxca128** [comment]
Hey @RandomMonkey99,  

Of course, I can help you with that! :)  

#### Step 1: Get a Custom Resource Pack  
First, you need a resource pack that includes the rank textures you want to display. For testing purposes, I used [Ranks for Fishing Datapack](https://www.planetminecraft.com/texture-pack/ranks-fishing-datapack/) by [BibekTheLegend](https://www.planetminecraft.com/member/bibekthelegend/).  

#### Step 2: Add the Resource Pack to Your Server  
You need to upload the resource pack to your server and ensure that players automatically download it. [This tutorial](https://www.youtube.com/watch?v=F-vxKzwir80&ab_channel=ZAP-Hosting) explains how to set up a server resource pack.  

#### Step 3: Set Up Your Ranks  
Now, let’s configure the ranks:  
1. Open the `ranks.yml` file.  
2. Create the ranks you need, assigning permissions, priorities, and other settings.  
3. Assign a custom texture to each rank using special characters.  

#### Step 4: Find the Correct Special Character  
Minecraft uses Unicode characters to reference custom textures from a resource pack. To determine the correct character for your rank:  
1. Open the resource pack and navigate to `assets/minecraft/font/default.json`.  
2. Look for the Unicode character mapping to the custom rank texture.  
3. Use that character in your rank prefix.  

For example, if your resource pack assigns `` to a specific rank, you would set:  
```yaml
Ranks:
  Player:
    Tab:
      Active: true
      Format: <white></white> <dark_gray>-</dark_gray> <aqua>{player}</aqua>
      Priority: 1
    Chat:
      Active: true
      Format: <white></white> <dark_gray>-</dark_gray> <aqua>{player}</aqua><dark_gray>:</dark_gray>
        <white>{message}</white>
    NameTag:
      Active: true
      Format: <white></white> <dark_gray>-</dark_gray> <aqua>{player}</aqua>
      HideOnSneak: true
    Permission: slimeranks.rank.player
```  

#### Step 4: Restart the server

Once set up correctly, the custom texture should appear in chat, tab, or above the player’s name (depending on your configuration).  

Let me know if you need further help! 🚀
